spring:
  freemarker:
    template-loader-path:
    - file:./views/templates/
  datasource:
    url: jdbc:mysql://localhost/spring-boot-security-demo?useSSL=false&characterEncoding=utf8
    username: root
    password: 123123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false

site:
  attempts: 5
  attemptsWaitTime: 15 # 单位分钟
  loginPoints: 2 # 登录点，最多2个位置登录，第三个登录点会覆盖第一个